### ISSUE TITLE
objectMode?

### ISSUE THREAD

**Issue by tallesl** [dominictarr/through#40]
It's possible to turn on [objectMode](https://nodejs.org/api/stream.html#stream_object_mode)?
[This note](https://github.com/dominictarr/through#extended-options) means that it doesn't support?

**Comment by jcrugzz** [comment]
There is no explicit `objectMode` because in `streams1` such a concept did not exist. This will work with `object` streams implicitly. if you want a module that supports `objectMode` you can use [`through2`](https://github.com/rvagg/through2)
