### ISSUE TITLE
Reduce the size of the npm package by limiting the included files

### ISSUE THREAD

**Issue by paazmaya** [dominictarr/through#50]
Looks like the `files` property (https://docs.npmjs.com/files/package.json#files) is not used in `package.json` to specify the included files, nor is the `.npmignore` file (https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) is being used for blacklisting unwanted files, for the package published to npm.

Would you consider adding either the `files` property or the `.npmignore` file, so that the resulting package file would have smaller size?

The current size can be seen when executing the command `npm pack` (https://docs.npmjs.com/cli/pack).

> This issue was create via [tawata](https://github.com/paazmaya/tawata/)

**Comment by dominictarr** [comment]
please do not use a bot to tell me that my modules could have some tests files removed. I don't care. I _like_ having tests in my module. I wrote hundreds of modules like this, I've got much better things to do than make tiny changes and the module already works just fine. ps. same here as with json-buffer
